#!/bin/bash

SCRIPT_FILE=`realpath "$0"`
SCRIPT_DIR=`dirname "$SCRIPT_FILE"`

INSTALL_DIR="$HOME/bin"

if [ ! -d "$INSTALL_DIR" ] ; then
	mkdir -p "$INSTALL_DIR"
fi

#echo SCRIPT_FILE=$SCRIPT_FILE
#echo SCRIPT_DIR=$SCRIPT_DIR
pushd "$SCRIPT_DIR" > /dev/null
for scr in *.sh ; do
	if [ -h "${INSTALL_DIR}/${scr%.*}" ] ; then
		ln -sf "${SCRIPT_DIR}/${scr}" "${INSTALL_DIR}/${scr%.*}"
	fi
	if [ ! -e "${INSTALL_DIR}/${scr%.*}" ] ; then
		ln -s "${SCRIPT_DIR}/${scr}" "${INSTALL_DIR}/${scr%.*}"
	fi
done
popd > /dev/null

PUBLIC_TEMPLATE=$HOME/script/template.tar.gz
if [ -f "$PUBLIC_TEMPLATE" ] ; then
	pushd $HOME > /dev/null
	tar zxf "$PUBLIC_TEMPLATE"
	popd
fi
PRIVATE_TEMPLATE=$HOME/config/template.tar.gz.gpg
if [ -f "$PRIVATE_TEMPLATE" ] ; then
	pushd $HOME > /dev/null
	gpg -d "$PRIVATE_TEMPLATE" | tar zxf -
	popd
fi

exit 0
